from pystardict import Dictionary

stardict = Dictionary("./dict/stardict")
PENN_TO_SIMPLE = {
    # Nouns
    'NN': 'noun',
    'NNS': 'noun',
    'NNP': 'noun',
    'NNPS': 'noun',
    
    # Verbs
    'VB': 'verb',
    'VBD': 'verb',
    'VBG': 'verb',
    'VBN': 'verb',
    'VBP': 'verb',
    'VBZ': 'verb',
    
    # Adjectives
    'JJ': 'adj',
    'JJR': 'adj',
    'JJS': 'adj',
    
    # Adverbs
    'RB': 'adv',
    'RBR': 'adv',
    'RBS': 'adv',
    'WRB': 'adv',
    
    # Pronouns
    'PRP': 'pron',
    'PRP$': 'pron',
    'WP': 'pron',
    'WP$': 'pron',
    
    # Determiners / Articles
    'DT': 'det',
    'PDT': 'det',
    'WDT': 'det',
    
    # Prepositions / Subordinating conjunctions
    'IN': 'prep',
    
    # Conjunctions
    'CC': 'conj',
    
    # Interjections
    'UH': 'interj',
    
    # Numbers
    'CD': 'num',
    
    # Modal verbs
    'MD': 'verb',
    
    # Particles
    'RP': 'part',
    
    # Symbols and punctuation
    '.': 'punct',
    ',': 'punct',
    ':': 'punct',
    '``': 'punct',
    "''": 'punct',
    '-LRB-': 'punct',
    '-RRB-': 'punct',
    '$': 'punct',
    '#': 'punct',
    'SYM': 'punct',
}


POS_DOBLE = {
             'a. &amp; v.':                         ['a.', 'v.'],
             'v. t. &amp; auxiliary.':              ['v. t.', 'auxiliary'],
             'pron. or adj.':                       ['pron.', 'adj.'],
             'imp., p. p., &amp; a.':               ['imp.', 'p. p.', 'a.'],
             'imp. &amp; archaic p. p.':            ['imp.', 'p. p.'],
             'adv. &amp; conj.':                    ['adv.', 'conj.'],
             'prep., adv., conj. &amp; n.':         ['prep.', 'adv.', 'conj.', 'n.'],
             'pron., a., &amp; adv.':               ['pron.', 'a.', 'adv.'],
             'imp., p. p., or auxiliary':           ['imp.', 'p. p.', 'auxiliary'],
             'adv. <plain>or</plain> prep.':        ['adv.', 'prep.'],
             'n. or interj.':                       ['n.', 'interj.'],
             'n. &amp; v. t. &amp; i.':             ['n.', 'v. t.', 'i.'],
             'n. sing. &amp; pl.':                  ['n. sing.', 'pl.'],
             'prop. a. &amp; n.':                   ['prop. a.', 'n.'],
             'prep. &amp; adv.':                    ['prep.', 'adv.'],
             'n. sing. or pl.':                     ['n. sing.', 'pl.'],
             'interj. &amp; n.':                    ['interj.', 'n.'],
             'n. &amp; adv.':                       ['n.', 'adv.'],
             'a. or adv.':                          ['a.', 'adv.'],
             'adv. &amp; n.':                       ['adv.', 'n.'],
             'pron. &amp; a.':                      ['pron.', 'a.'],
             'n. &amp; v. t.':                      ['n.', 'v. t.'],
             'imp. &amp; obs. p. p.':               ['imp.', 'obs. p. p.'],
             'p. p. or a.':                         ['p. p.', 'a.'],
             'p. pr. &amp; vb. n.':                 ['p. pr.', 'vb. n.'],
             'interj. &amp; adv.':                  ['interj', 'adv.'],
             'inf. &amp; plural pres.':             ['inf.', 'plural pres.'],
             'v. t. &amp; n.':                      ['v. t.', 'n.'],
             'a. or n.':                            ['a.', 'n.'],
             'adv. &amp; prep.':                    ['adv.', 'prep.'],
             'a. or a. pron.':                      ['a.', 'a. pron.'],
             'a., n., &amp; adv.':                  ['a.' 'n.', 'adv.'],
             'v. i. &amp; auxiliary.':              ['v. i.', 'auxiliary'],
             'a &amp; n.':                          ["a", "n."],
             'a. &amp; n.':                         ['a.', 'n.'],
             'a. &amp; pron.':                      ['a.', 'pron.'],
             'prep. &amp; conj.':                   ['prep.', 'conj.'],
             'pron., a., conj., &amp; adv.':        ['pron.' 'a.', 'conj.', 'adv.'],
             'p. pr. &amp; a.':                     ['p. pr.', 'a.'],
             'v. t. &amp; i.':                      ['v. t.', 'i.'],
             'prep., adv., &amp; conj.':            ['prep.', 'adv.', 'conj.'],
             'p. p. &amp; a.':                      ['p. p.', 'a.'],
             'n. &amp; adj.':                       ['n.', 'adj.'],
             'adj. &amp; adv.':                     ['adj.', 'adv.'],
             'adv. &amp; a.':                       ['adv.', 'a.'],
             'adv. or a.':                          ['adv.', 'a.'],
             'p. &amp; a.':                         ['p.', 'a.'],
             'a. &amp; adv.':                       ['a.', 'adv.'],
             'pron. &amp; conj.':                   ['pron.', 'conj.'],
             'adj. &amp; conj.':                    ['adj.', 'conj.'],
             'n. &amp; v. i.':                      ['n.', 'v. i.'],
             'adv. or conj.':                       ['adv.', 'conj.'],
             'a. &amp; v. t.':                      ['a.', 'v. t.'],
             'imp. &amp; p. p. or a.':              ['imp.', 'p. p.', 'a.'],
             'n. &amp; a.':                         ['n.', 'a.'],
             'p. a. &amp; vb. n.':                  ['p. a.', 'vb. n.'],
             'v. i. &amp; n.':                      ['v. i.', 'n.'],
             'p. p &amp; a.':                       ['p. p', 'a.'],
             'n. collect. &amp; pl.':               ['n.', 'pl.'],
             'a. &amp; p. p.':                      ['a.', 'p. p.'],
             'imp. pl. &amp; p. p.':                ['imp.', 'p. p.'],
             'adv., prep., &amp; conj.':            ['adv.', 'prep.', 'conj.'],
             'interj., adv., &amp; n.':             ['interj.', 'adv.', 'n.'],
             'a. or pron.':                         ['a.', 'pron.'],
             'a. &amp; poss. pron.':                ['a.', 'pron.'],
             'imp. &amp; p. p.':                    ['imp.', 'p. p.'],
             'n. &amp; interj.':                    ['n.', 'interj.'],
             'n. &amp; v.':                         ['n.', 'v.'],
             'adv. or interj.':                     ['adv.', 'interj.'],
             'prep., adv. &amp; a.':                ['prep.', 'adv.', 'a.'],
             'conj. &amp; prep.':                   ['conj.', 'prep.'],
             'v. &amp; n.':                         ['v.', 'n.'],
             'conj. &amp; adv.':                    ['conj.', 'adv.'],
             'interj., adv., or a.':                ['interj.', 'adv.', 'a.'],
             'n., a., &amp; v.':                    ['n.', 'a.', 'v.'],
             'prep. or conj.':                      ['prep.', 'conj.'],
             'a. &amp; vb. n.':                     ['a.', 'vb. n.'],
             'p. pr. &amp; rare vb. n.':            ['p. pr.', 'v.'],
             'a., adv., &amp; n.':                  ['a.', 'adv.', 'n.'],
             'adv.orprep.':                         ['adv.', 'prep.'],
             'adv. &amp; pref':                     ['adv', 'verb'],
             'adv. &amp; pref.':                    ['adv', 'verb'],
             'conj. or adv.':                       ['conj', 'adv'],
             'p. pr., a., &amp; vb. n.':            ['adj', 'verb'],
             'adv. &amp; adj.':                     ['adv', 'adj'],
             'a.;alsoadv.':                         ['adj', 'adv'],

             }


DICT_TO_SIMPLE = {
    'abl.': 'other',
    '1st &amp; 3d pers. sing. pres.': 'verb',
    'pr. n. pl.': 'noun',
    'imperative.': 'verb',
    'm.': 'noun',
    'n.pl.': 'noun',
    'PROP. n. pl.': 'noun',
    'n. sing &amp; pl.': 'noun',
    'n. pl. &amp; sing.': 'noun',
    'v. t. &amp; v. i.': 'verb',
    'imp. sing. &amp; 2d pers. pl.': 'verb',
    'masc. a.': 'adj',
    'p. p., fem.': 'verb',
    'prop. n. sing. &amp; pl.': 'noun',
    'n. m.': 'noun',
    'a. m.': 'adj',
    'pres. &amp; imp. sing. &amp; pl': 'verb',
    'n. sing. &amp;  pl.': 'noun',
    'pres. &amp; imp. sing. &amp; pl.': 'verb',
    'n.sing. &amp; pl.': 'noun',
    'a. &amp; a. pron.':                   'adj',
    'pres. indic., 1st &amp; 3d pers. sing.': 'verb',
    'pres. indic. 1st &amp; 3d pers. sing.': 'verb',
    'v. t. &amp;  i.':                    'verb',
    'Prop. n.':                           'noun',
    'v. i. &amp; i.':                     'verb',
    'n., sing. &amp; pl.': 'noun',
    'v. i. &amp; t.':   'verb',
    'v. t. &amp; \ni.':  'verb',
    'sing. pres.': 'verb',
    'interrog. adv.': 'adv',
    'inf.': 'verb',
    'def. art.': 'det',
    'pron.': 'pron',
    'suffix.': 'other',
    'v. impers.': 'verb',
    'pres. indic. 1st & 3d pers. sing.': 'verb',
    '3d pers. sing. pres.': 'verb',
    'a.': 'adj',
    'p.': 'other',
    'peop. n.': 'noun',
    'pron.a.': 'pron',
    'contrac.': 'other',
    '3d sing. pr.': 'verb',
    'adv. & pref.': 'adv',
    '3d sing. pres.': 'verb',
    'n. pl': 'noun',
    'imp.': 'verb',
    'adj.': 'adj',
    'pref.': 'other',
    'pers. pron.': 'pron',
    'obs. imp. pl.': 'verb',
    'n. fem.': 'noun',
    'v. i. & i.': 'verb',
    'imperative sing.': 'verb',
    'a. superl.': 'adj',
    'prop. a.': 'adj',
    'prop. n.': 'noun',
    'p. pr.': 'verb',
    'prefix.': 'other',
    'imp. sing.': 'verb',
    'vb. n.': 'verb',
    'v. i. or auxiliary': 'verb',
    'imp. pl.': 'verb',
    'obs. imp.': 'verb',
    'indef. pron.': 'pron',
    '3d pers. sing. present': 'verb',
    'v. t. &  i.': 'verb',
    'interj.': 'interj',
    'n': 'noun',
    'prop. n. sing. & pl.': 'noun',
    'ads.': 'adv',
    '2d pers. sing. imp.': 'verb',
    'n..': 'noun',
    'pl. indic. pr.': 'verb',
    '2d pers. sing. pres.': 'verb',
    'pret.': 'verb',
    '3d pers. pres.': 'verb',
    'n. f.': 'noun',
    'third pers. sing. pres.': 'verb',
    '3d. pers. sing. pres.': 'verb',
    'prop. v. i.': 'verb',
    'prep. phr.': 'prep',
    'poss. pron.': 'pron',
    'prep.': 'prep',
    'v. t. or v. i.': 'verb',
    'i.': 'other',
    'conj.': 'conj',
    'n. sing. &  pl.': 'noun',
    'definite article.': 'det',
    'v. impersonal, pres.': 'verb',
    'v. i.': 'verb',
    'n.': 'noun',
    'Compar.': 'adj',
    'suff.': 'other',
    'pred. a.': 'adj',
    'n. masc.': 'noun',
    'possessive pron.': 'pron',
    'obs. 3d pers. sing. pres.': 'verb',
    'a. compar.': 'adj',
    'subj. 3d pers. sing.': 'verb',
    'v., 3d pers. sing. pres.': 'verb',
    'p. p': 'verb',
    'superl.': 'adj',
    'a. .': 'adj',
    'v. t.': 'verb',
    'a., compar.': 'adj',
    'pr. n.': 'noun',
    'a. & a. pron.': 'adj',
    'obs. p. p.': 'verb',
    'plural pres.': 'verb',
    'prop. v. t.': 'verb',
    'a.; also adv.': 'adj',
    'suffix': 'other',
    'v. inf.': 'verb',
    'pres. & imp. sing. & pl.': 'verb',
    'fem.': 'noun',
    'p. p.': 'verb',
    'v. n.': 'verb',
    'imp. (and rare p. p.)': 'verb',
    'pl. pres.': 'verb',
    'prop. n. pl.': 'noun',
    'pl.': 'noun',
    'a.n.': 'adj',
    'compar.': 'adj',
    'p. pr., a., & vb. n.': 'verb',
    'v. t. & v. i.': 'verb',
    'strong imp.': 'verb',
    'pr. a.': 'adj',
    'a. ': 'adj',
    'a': 'adj',
    'prop. prop. n.': 'noun',
    'adv.': 'adv',
    'n. pl.': 'noun',
    'auxiliary': 'verb',
    'pres. indic., 1st & 3d pers. sing.': 'verb',
    'prop. adj.': 'adj',
    'n. sing.': 'noun',
    'n. pl., but sing. or pl. in usage': 'noun',
    '1st & 3d pers. sing. pres.': 'verb',
    '3d pers. sing. pr.': 'verb',
    'imp. sing. & 2d pers. pl.': 'verb',
    'interj': 'interj',
    'a. pron.': 'pron',
    'p. a.': 'adj',
    '2d pers. sing.': 'verb',
    '2d per. sing.': 'verb',
    '2d pers. pl.': 'verb',
    'p.a.': 'adj',
    'pron. pl.': 'pron',
    'n.sing. & pl.': 'noun',
    '3d pers. sing.': 'verb',
    'v.': 'verb',
    'unk' :'other',
}
POS_SET = {'prep', 'det', 'noun', 'other', 'adv', 'adj', 'verb', 'interj', 'pron', 'conj'}

if __name__ == "__main__":
    pos_set = []
    for v in DICT_TO_SIMPLE.values():
        pos_set.append(v)
    print(set(pos_set))
